script:
  - bundle exec rake db:migrate spec RAILS_ENV=test
env:
  - GEM=core
  - GEM=pages
  - GEM=attachments
before_install:
  - unset BUNDLE_GEMFILE
  - gem update --system
  - gem --version
  - gem install bundler
  - cd $GEM
rvm:
  - 2.1.5
  - 2.2.0
